//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArqui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoArqui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 0 4 4
        ///8 0 1 15 
        ///8 0 20 24
        ///8 0 2 0
        ///8 0 5 1000
        ///8 5 5 -1
        ///5 5 0 -2
        ///43 2 1 0
        ///43 2 1 4
        ///43 2 1 8
        ///43 2 1 12
        ///34 20 4 20
        ///8 2 2 16
        ///5 20 0 -10
        ///8 0 31 99
        ///43 0 31 100
        ///35 0 13 92
        ///35 0 12 0
        ///35 0 14 28
        ///35 0 15 120
        ///63 0 0 0
        ///.
        /// </summary>
        internal static string Hilo1 {
            get {
                return ResourceManager.GetString("Hilo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 0 4 5
        ///8 0 2 -48
        ///8 0 28 25
        ///8 0 16 88
        ///8 0 5 1000
        ///43 16 2 0
        ///43 16 2 -4
        ///43 16 2 -8
        ///43 16 2 -12
        ///34 28 4 28
        ///8 16 16 -16
        ///8 5 5 -1
        ///5 5 0 -2
        ///5 28 0 -10
        ///8 0 31 77
        ///43 0 31 0
        ///35 0 13 92
        ///35 0 11 100
        ///35 0 14 28
        ///35 0 15 120
        ///63 0 0 0
        ///.
        /// </summary>
        internal static string Hilo2 {
            get {
                return ResourceManager.GetString("Hilo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 0 4 5
        ///8 0 3 3
        ///8 0 28 15
        ///8 0 24 104
        ///8 0 5 1000
        ///43 24 3 0
        ///43 24 3 4
        ///8 5 5 -1
        ///5 5 0 -2
        ///34 28 4 28
        ///8 24 24 8
        ///5 28 0 -8
        ///8 0 31 55
        ///43 0 31 92
        ///35 0 11 96
        ///35 0 12 104
        ///35 0 14 28
        ///35 0 15 0
        ///63 0 0 0
        ///
        ///.
        /// </summary>
        internal static string Hilo3 {
            get {
                return ResourceManager.GetString("Hilo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 0 4 222
        ///8 0 3 0
        ///34 30 30 30
        ///34 10 10 10
        ///8 0 25 72
        ///8 0 8 8
        ///35 25 5 0
        ///35 25 6 4
        ///32 5 6 3
        ///32 30 3 30
        ///43 25 4 0
        ///43 25 4 4
        ///35 25 5 8
        ///35 25 6 12
        ///32 5 6 10
        ///43 25 4 8
        ///43 25 4 12
        ///32 30 10 30
        ///8 8 8 -4
        ///8 25 25 16
        ///5 8 0 -15
        ///43 0 30 20
        ///4 8 0 1
        ///43 0 25 24
        ///8 0 31 44
        ///43 0 31 28
        ///35 0 11 100
        ///35 0 12 0
        ///35 0 13 104
        ///35 0 15 120
        ///63 0 0 0
        ///.
        /// </summary>
        internal static string Hilo4 {
            get {
                return ResourceManager.GetString("Hilo4", resourceCulture);
            }
        }
    }
}
